import { post, get } from './request'
export const activityListApi = (data) => post('/client/Activity/activityList', data)
export const activityCateApi = (data) => post('/client/Activity/activityCate', data)
export const activeDetailApi = (data) => post('/client/Activity/detail', data)
export const loginByCode = (data) => post('/client/weixin/loginByCode', data)
export const indexInfo = (data) => post('/client/index/index', data)
export const indexHistoryList = (data) => post('/client/Activity/historyList', data)
export const newsCate = (data) => post('/client/Celebrity/newsCate', data)
export const celebrity = (data) => post('/client/celebrity/index', data)
export const celebrityDetail = (data) => post('/client/celebrity/detail', data)
export const mallGoodsindex = (data) => post('/mall/goods/index', data)
export const mallGoodDetail = (data) => post('/mall/goods/detail', data)
export const articleAboutus = (data) => post('/client/article/aboutus', data)
export const mallAddressIndex = (data) => get('/mall/address/index?token=' + data.token)
export const mallAddressEdit = (data) => post('/mall/address/edit', data)
export const indexCityData = (data) => get('/client/index/cityData?token=' + data.token)
export const mallAddressDel = (data) => post('/mall/address/del', data)
export const mallAddressAdd = (data) => post('/mall/address/add', data)
export const mallOrderBuyView = (data) => post('/mall/order/buyView', data)
export const mallOrderBuy = (data) => post('/mall/order/buy', data)
export const weixinGetShare = (data) => post('/client/weixin/getShare', data)
export const ticketListApi = (data) => post('/mall/Ticket/index', data)
export const ticketCateApi = (data) => post('/mall/Ticket/ticketCate', data)
export const ticketDetailApi = (data) => post('/mall/Ticket/detail', data)
export const ticketPaylApi = (data) => post('/mall/ticket_order/buyView', data)
export const orderLisApi = (data) => get(`/mall/order/orderLis?status=${data}`)
export const orderList = (data) => get(`/mall/order/orderList?status=${data.status}&token=${data.token}&page=${data.page}&page_size=${data.page_size}`)
export const mallOrderKeepPay = (data) => post('/mall/order/keepPay', data)
export const mallOrderOrderDetail = (data) => post('/mall/order/orderDetail', data)
export const mallCloseOrder = (data) => post('/mall/order/closeOrder', data)
